// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-stores.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-stores.ts
var list_stores_default = defineTool({
  name: "list_stores",
  title: "List stores",
  description: "List the signed-in distributor's storefronts with status, slug and type.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of stores to return."),
    status: z.string().trim().optional().describe("Optional status filter, e.g. 'active'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("stores").select("id, store_name, client_name, slug, status, store_type, domain, custom_domain, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { stores: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-store.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_store_default = defineTool2({
  name: "get_store",
  title: "Get store details",
  description: "Fetch full configuration for one storefront by id or slug.",
  inputSchema: {
    store_id: z2.string().uuid().optional().describe("Store id (uuid)."),
    slug: z2.string().trim().min(1).optional().describe("Store slug, used when no id is given.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ store_id, slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    if (!store_id && !slug) return { content: [{ type: "text", text: "Provide store_id or slug" }], isError: true };
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("stores").select("*").limit(1);
    query = store_id ? query.eq("id", store_id) : query.eq("slug", slug);
    const { data, error } = await query.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Store not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { store: data }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_orders_default = defineTool3({
  name: "list_orders",
  title: "List orders",
  description: "List orders across the signed-in distributor's storefronts, newest first.",
  inputSchema: {
    store_id: z3.string().uuid().optional().describe("Restrict to a single store id."),
    status: z3.string().trim().optional().describe("Optional status filter, e.g. 'pending'."),
    limit: z3.number().int().min(1).max(100).default(25).describe("Maximum number of orders to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ store_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser(ctx).from("orders").select("id, store_id, customer_name, customer_email, total, status, items, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (store_id) query = query.eq("store_id", store_id);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/update-order-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var update_order_status_default = defineTool4({
  name: "update_order_status",
  title: "Update order status",
  description: "Set the status of one order belonging to the signed-in distributor.",
  inputSchema: {
    order_id: z4.string().uuid().describe("Order id (uuid)."),
    status: z4.string().trim().min(1).describe("New status value, e.g. 'pending', 'in_production', 'shipped', 'delivered', 'cancelled'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("orders").update({ status }).eq("id", order_id).select("id, status, store_id, customer_name, total").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Order not found or not accessible" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/search-catalog.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var search_catalog_default = defineTool5({
  name: "search_catalog",
  title: "Search product catalog",
  description: "Search the Brand-Shop Catalog of blank apparel by title, brand or category.",
  inputSchema: {
    query: z5.string().trim().min(1).describe("Search text matched against product title and brand."),
    category: z5.string().trim().optional().describe("Optional base category filter."),
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum number of products to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const escaped = query.replace(/[%,]/g, " ").trim();
    let request = supabaseForUser(ctx).from("ss_catalog_cache").select("style_id, title, brand_name, base_category, style_image_url, pricing, total_skus").or(`title.ilike.%${escaped}%,brand_name.ilike.%${escaped}%`).limit(limit ?? 20);
    if (category) request = request.eq("base_category", category);
    const { data, error } = await request;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zqjfpolkmfzzgszmlifq";
var mcp_default = defineMcp({
  name: "brand-shop-ai",
  title: "Brand-Shop AI",
  version: "0.1.0",
  instructions: "Tools for Brand-Shop AI. Use `list_stores` and `get_store` to inspect the signed-in distributor's storefronts, `list_orders` and `update_order_status` to manage orders, and `search_catalog` to look up blank apparel products.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_stores_default, get_store_default, list_orders_default, update_order_status_default, search_catalog_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
